services:
  server:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: ${PROJECT}-server
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ../../.env
    depends_on:
      - redis-stack
    restart: always

  redis-stack:
    image: redis/redis-stack
    container_name: ${PROJECT}-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: on-failure

  gateway:
    image: nginx:alpine
    container_name: ${PROJECT}-gateway
    ports:
      - "80:80"
    volumes:
      - ../../config.d/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../config.d/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf

volumes:
  redis_data:
