/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  User: 'User',
  Verification: 'Verification',
  SocialAccount: 'SocialAccount',
  Community: 'Community',
  CommunityFollower: 'CommunityFollower',
  ChatChannel: 'ChatChannel',
  ChatParticipant: 'ChatParticipant',
  ChatMessage: 'ChatMessage',
  Post: 'Post',
  Comment: 'Comment',
  PostLike: 'PostLike',
  PostView: 'PostView'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  email: 'email',
  username: 'username',
  password: 'password',
  role: 'role',
  deviceToken: 'deviceToken',
  avatarUrl: 'avatarUrl',
  backgroundUrl: 'backgroundUrl',
  bio: 'bio',
  communityId: 'communityId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  type: 'type',
  token: 'token',
  expiresAt: 'expiresAt',
  userId: 'userId',
  usedAt: 'usedAt',
  confirmedAt: 'confirmedAt',
  email: 'email'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const SocialAccountScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  provider: 'provider',
  providerId: 'providerId',
  userId: 'userId'
} as const

export type SocialAccountScalarFieldEnum = (typeof SocialAccountScalarFieldEnum)[keyof typeof SocialAccountScalarFieldEnum]


export const CommunityScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  name: 'name',
  avatarUrl: 'avatarUrl',
  backgroundUrl: 'backgroundUrl',
  description: 'description'
} as const

export type CommunityScalarFieldEnum = (typeof CommunityScalarFieldEnum)[keyof typeof CommunityScalarFieldEnum]


export const CommunityFollowerScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  userId: 'userId',
  communityId: 'communityId'
} as const

export type CommunityFollowerScalarFieldEnum = (typeof CommunityFollowerScalarFieldEnum)[keyof typeof CommunityFollowerScalarFieldEnum]


export const ChatChannelScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  name: 'name',
  description: 'description',
  type: 'type',
  communityId: 'communityId',
  idolId: 'idolId',
  isAnnouncement: 'isAnnouncement',
  lastMessageAt: 'lastMessageAt',
  firebaseDocId: 'firebaseDocId'
} as const

export type ChatChannelScalarFieldEnum = (typeof ChatChannelScalarFieldEnum)[keyof typeof ChatChannelScalarFieldEnum]


export const ChatParticipantScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  channelId: 'channelId',
  userId: 'userId',
  role: 'role',
  lastReadAt: 'lastReadAt',
  unreadCount: 'unreadCount',
  isMuted: 'isMuted'
} as const

export type ChatParticipantScalarFieldEnum = (typeof ChatParticipantScalarFieldEnum)[keyof typeof ChatParticipantScalarFieldEnum]


export const ChatMessageScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  content: 'content',
  channelId: 'channelId',
  userId: 'userId'
} as const

export type ChatMessageScalarFieldEnum = (typeof ChatMessageScalarFieldEnum)[keyof typeof ChatMessageScalarFieldEnum]


export const PostScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  content: 'content',
  likeCount: 'likeCount',
  commentCount: 'commentCount',
  viewCount: 'viewCount',
  authorId: 'authorId'
} as const

export type PostScalarFieldEnum = (typeof PostScalarFieldEnum)[keyof typeof PostScalarFieldEnum]


export const CommentScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  content: 'content',
  postId: 'postId',
  userId: 'userId',
  parentId: 'parentId'
} as const

export type CommentScalarFieldEnum = (typeof CommentScalarFieldEnum)[keyof typeof CommentScalarFieldEnum]


export const PostLikeScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  postId: 'postId',
  userId: 'userId'
} as const

export type PostLikeScalarFieldEnum = (typeof PostLikeScalarFieldEnum)[keyof typeof PostLikeScalarFieldEnum]


export const PostViewScalarFieldEnum = {
  id: 'id',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  version: 'version',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  metadata: 'metadata',
  postId: 'postId',
  userId: 'userId'
} as const

export type PostViewScalarFieldEnum = (typeof PostViewScalarFieldEnum)[keyof typeof PostViewScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

