
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ChatChannel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ChatChannel
 * 
 */
export type ChatChannelModel = runtime.Types.Result.DefaultSelection<Prisma.$ChatChannelPayload>

export type AggregateChatChannel = {
  _count: ChatChannelCountAggregateOutputType | null
  _avg: ChatChannelAvgAggregateOutputType | null
  _sum: ChatChannelSumAggregateOutputType | null
  _min: ChatChannelMinAggregateOutputType | null
  _max: ChatChannelMaxAggregateOutputType | null
}

export type ChatChannelAvgAggregateOutputType = {
  version: number | null
}

export type ChatChannelSumAggregateOutputType = {
  version: number | null
}

export type ChatChannelMinAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  name: string | null
  description: string | null
  type: $Enums.ChatChannelType | null
  groupId: string | null
  idolId: string | null
  isAnnouncement: boolean | null
  lastMessageAt: Date | null
  firebaseDocId: string | null
}

export type ChatChannelMaxAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  name: string | null
  description: string | null
  type: $Enums.ChatChannelType | null
  groupId: string | null
  idolId: string | null
  isAnnouncement: boolean | null
  lastMessageAt: Date | null
  firebaseDocId: string | null
}

export type ChatChannelCountAggregateOutputType = {
  id: number
  isActive: number
  createdAt: number
  updatedAt: number
  version: number
  name: number
  description: number
  type: number
  groupId: number
  idolId: number
  isAnnouncement: number
  lastMessageAt: number
  firebaseDocId: number
  _all: number
}


export type ChatChannelAvgAggregateInputType = {
  version?: true
}

export type ChatChannelSumAggregateInputType = {
  version?: true
}

export type ChatChannelMinAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  name?: true
  description?: true
  type?: true
  groupId?: true
  idolId?: true
  isAnnouncement?: true
  lastMessageAt?: true
  firebaseDocId?: true
}

export type ChatChannelMaxAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  name?: true
  description?: true
  type?: true
  groupId?: true
  idolId?: true
  isAnnouncement?: true
  lastMessageAt?: true
  firebaseDocId?: true
}

export type ChatChannelCountAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  name?: true
  description?: true
  type?: true
  groupId?: true
  idolId?: true
  isAnnouncement?: true
  lastMessageAt?: true
  firebaseDocId?: true
  _all?: true
}

export type ChatChannelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChatChannel to aggregate.
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatChannels to fetch.
   */
  orderBy?: Prisma.ChatChannelOrderByWithRelationInput | Prisma.ChatChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChatChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ChatChannels
  **/
  _count?: true | ChatChannelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ChatChannelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ChatChannelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChatChannelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChatChannelMaxAggregateInputType
}

export type GetChatChannelAggregateType<T extends ChatChannelAggregateArgs> = {
      [P in keyof T & keyof AggregateChatChannel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChatChannel[P]>
    : Prisma.GetScalarType<T[P], AggregateChatChannel[P]>
}




export type ChatChannelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatChannelWhereInput
  orderBy?: Prisma.ChatChannelOrderByWithAggregationInput | Prisma.ChatChannelOrderByWithAggregationInput[]
  by: Prisma.ChatChannelScalarFieldEnum[] | Prisma.ChatChannelScalarFieldEnum
  having?: Prisma.ChatChannelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChatChannelCountAggregateInputType | true
  _avg?: ChatChannelAvgAggregateInputType
  _sum?: ChatChannelSumAggregateInputType
  _min?: ChatChannelMinAggregateInputType
  _max?: ChatChannelMaxAggregateInputType
}

export type ChatChannelGroupByOutputType = {
  id: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  version: number
  name: string | null
  description: string | null
  type: $Enums.ChatChannelType
  groupId: string | null
  idolId: string | null
  isAnnouncement: boolean
  lastMessageAt: Date | null
  firebaseDocId: string
  _count: ChatChannelCountAggregateOutputType | null
  _avg: ChatChannelAvgAggregateOutputType | null
  _sum: ChatChannelSumAggregateOutputType | null
  _min: ChatChannelMinAggregateOutputType | null
  _max: ChatChannelMaxAggregateOutputType | null
}

type GetChatChannelGroupByPayload<T extends ChatChannelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChatChannelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChatChannelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChatChannelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChatChannelGroupByOutputType[P]>
      }
    >
  >



export type ChatChannelWhereInput = {
  AND?: Prisma.ChatChannelWhereInput | Prisma.ChatChannelWhereInput[]
  OR?: Prisma.ChatChannelWhereInput[]
  NOT?: Prisma.ChatChannelWhereInput | Prisma.ChatChannelWhereInput[]
  id?: Prisma.StringFilter<"ChatChannel"> | string
  isActive?: Prisma.BoolFilter<"ChatChannel"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  version?: Prisma.IntFilter<"ChatChannel"> | number
  name?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  description?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  type?: Prisma.EnumChatChannelTypeFilter<"ChatChannel"> | $Enums.ChatChannelType
  groupId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  idolId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  isAnnouncement?: Prisma.BoolFilter<"ChatChannel"> | boolean
  lastMessageAt?: Prisma.DateTimeNullableFilter<"ChatChannel"> | Date | string | null
  firebaseDocId?: Prisma.StringFilter<"ChatChannel"> | string
  group?: Prisma.XOR<Prisma.GroupNullableScalarRelationFilter, Prisma.GroupWhereInput> | null
  idol?: Prisma.XOR<Prisma.IdolNullableScalarRelationFilter, Prisma.IdolWhereInput> | null
  participants?: Prisma.ChatParticipantListRelationFilter
}

export type ChatChannelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  idolId?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnnouncement?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrderInput | Prisma.SortOrder
  firebaseDocId?: Prisma.SortOrder
  group?: Prisma.GroupOrderByWithRelationInput
  idol?: Prisma.IdolOrderByWithRelationInput
  participants?: Prisma.ChatParticipantOrderByRelationAggregateInput
}

export type ChatChannelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  firebaseDocId?: string
  AND?: Prisma.ChatChannelWhereInput | Prisma.ChatChannelWhereInput[]
  OR?: Prisma.ChatChannelWhereInput[]
  NOT?: Prisma.ChatChannelWhereInput | Prisma.ChatChannelWhereInput[]
  isActive?: Prisma.BoolFilter<"ChatChannel"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  version?: Prisma.IntFilter<"ChatChannel"> | number
  name?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  description?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  type?: Prisma.EnumChatChannelTypeFilter<"ChatChannel"> | $Enums.ChatChannelType
  groupId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  idolId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  isAnnouncement?: Prisma.BoolFilter<"ChatChannel"> | boolean
  lastMessageAt?: Prisma.DateTimeNullableFilter<"ChatChannel"> | Date | string | null
  group?: Prisma.XOR<Prisma.GroupNullableScalarRelationFilter, Prisma.GroupWhereInput> | null
  idol?: Prisma.XOR<Prisma.IdolNullableScalarRelationFilter, Prisma.IdolWhereInput> | null
  participants?: Prisma.ChatParticipantListRelationFilter
}, "id" | "firebaseDocId">

export type ChatChannelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  idolId?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnnouncement?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrderInput | Prisma.SortOrder
  firebaseDocId?: Prisma.SortOrder
  _count?: Prisma.ChatChannelCountOrderByAggregateInput
  _avg?: Prisma.ChatChannelAvgOrderByAggregateInput
  _max?: Prisma.ChatChannelMaxOrderByAggregateInput
  _min?: Prisma.ChatChannelMinOrderByAggregateInput
  _sum?: Prisma.ChatChannelSumOrderByAggregateInput
}

export type ChatChannelScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChatChannelScalarWhereWithAggregatesInput | Prisma.ChatChannelScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChatChannelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChatChannelScalarWhereWithAggregatesInput | Prisma.ChatChannelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ChatChannel"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"ChatChannel"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ChatChannel"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ChatChannel"> | Date | string
  version?: Prisma.IntWithAggregatesFilter<"ChatChannel"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"ChatChannel"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"ChatChannel"> | string | null
  type?: Prisma.EnumChatChannelTypeWithAggregatesFilter<"ChatChannel"> | $Enums.ChatChannelType
  groupId?: Prisma.StringNullableWithAggregatesFilter<"ChatChannel"> | string | null
  idolId?: Prisma.StringNullableWithAggregatesFilter<"ChatChannel"> | string | null
  isAnnouncement?: Prisma.BoolWithAggregatesFilter<"ChatChannel"> | boolean
  lastMessageAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ChatChannel"> | Date | string | null
  firebaseDocId?: Prisma.StringWithAggregatesFilter<"ChatChannel"> | string
}

export type ChatChannelCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  group?: Prisma.GroupCreateNestedOneWithoutChatChannelsInput
  idol?: Prisma.IdolCreateNestedOneWithoutChatChannelsInput
  participants?: Prisma.ChatParticipantCreateNestedManyWithoutChannelInput
}

export type ChatChannelUncheckedCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  groupId?: string | null
  idolId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  participants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutChannelInput
}

export type ChatChannelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.GroupUpdateOneWithoutChatChannelsNestedInput
  idol?: Prisma.IdolUpdateOneWithoutChatChannelsNestedInput
  participants?: Prisma.ChatParticipantUpdateManyWithoutChannelNestedInput
}

export type ChatChannelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idolId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  participants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutChannelNestedInput
}

export type ChatChannelCreateManyInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  groupId?: string | null
  idolId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
}

export type ChatChannelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatChannelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idolId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatChannelListRelationFilter = {
  every?: Prisma.ChatChannelWhereInput
  some?: Prisma.ChatChannelWhereInput
  none?: Prisma.ChatChannelWhereInput
}

export type ChatChannelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChatChannelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  idolId?: Prisma.SortOrder
  isAnnouncement?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  firebaseDocId?: Prisma.SortOrder
}

export type ChatChannelAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type ChatChannelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  idolId?: Prisma.SortOrder
  isAnnouncement?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  firebaseDocId?: Prisma.SortOrder
}

export type ChatChannelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  idolId?: Prisma.SortOrder
  isAnnouncement?: Prisma.SortOrder
  lastMessageAt?: Prisma.SortOrder
  firebaseDocId?: Prisma.SortOrder
}

export type ChatChannelSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type ChatChannelScalarRelationFilter = {
  is?: Prisma.ChatChannelWhereInput
  isNot?: Prisma.ChatChannelWhereInput
}

export type ChatChannelCreateNestedManyWithoutIdolInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput> | Prisma.ChatChannelCreateWithoutIdolInput[] | Prisma.ChatChannelUncheckedCreateWithoutIdolInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutIdolInput | Prisma.ChatChannelCreateOrConnectWithoutIdolInput[]
  createMany?: Prisma.ChatChannelCreateManyIdolInputEnvelope
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
}

export type ChatChannelUncheckedCreateNestedManyWithoutIdolInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput> | Prisma.ChatChannelCreateWithoutIdolInput[] | Prisma.ChatChannelUncheckedCreateWithoutIdolInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutIdolInput | Prisma.ChatChannelCreateOrConnectWithoutIdolInput[]
  createMany?: Prisma.ChatChannelCreateManyIdolInputEnvelope
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
}

export type ChatChannelUpdateManyWithoutIdolNestedInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput> | Prisma.ChatChannelCreateWithoutIdolInput[] | Prisma.ChatChannelUncheckedCreateWithoutIdolInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutIdolInput | Prisma.ChatChannelCreateOrConnectWithoutIdolInput[]
  upsert?: Prisma.ChatChannelUpsertWithWhereUniqueWithoutIdolInput | Prisma.ChatChannelUpsertWithWhereUniqueWithoutIdolInput[]
  createMany?: Prisma.ChatChannelCreateManyIdolInputEnvelope
  set?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  disconnect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  delete?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  update?: Prisma.ChatChannelUpdateWithWhereUniqueWithoutIdolInput | Prisma.ChatChannelUpdateWithWhereUniqueWithoutIdolInput[]
  updateMany?: Prisma.ChatChannelUpdateManyWithWhereWithoutIdolInput | Prisma.ChatChannelUpdateManyWithWhereWithoutIdolInput[]
  deleteMany?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
}

export type ChatChannelUncheckedUpdateManyWithoutIdolNestedInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput> | Prisma.ChatChannelCreateWithoutIdolInput[] | Prisma.ChatChannelUncheckedCreateWithoutIdolInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutIdolInput | Prisma.ChatChannelCreateOrConnectWithoutIdolInput[]
  upsert?: Prisma.ChatChannelUpsertWithWhereUniqueWithoutIdolInput | Prisma.ChatChannelUpsertWithWhereUniqueWithoutIdolInput[]
  createMany?: Prisma.ChatChannelCreateManyIdolInputEnvelope
  set?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  disconnect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  delete?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  update?: Prisma.ChatChannelUpdateWithWhereUniqueWithoutIdolInput | Prisma.ChatChannelUpdateWithWhereUniqueWithoutIdolInput[]
  updateMany?: Prisma.ChatChannelUpdateManyWithWhereWithoutIdolInput | Prisma.ChatChannelUpdateManyWithWhereWithoutIdolInput[]
  deleteMany?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
}

export type ChatChannelCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput> | Prisma.ChatChannelCreateWithoutGroupInput[] | Prisma.ChatChannelUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutGroupInput | Prisma.ChatChannelCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.ChatChannelCreateManyGroupInputEnvelope
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
}

export type ChatChannelUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput> | Prisma.ChatChannelCreateWithoutGroupInput[] | Prisma.ChatChannelUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutGroupInput | Prisma.ChatChannelCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.ChatChannelCreateManyGroupInputEnvelope
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
}

export type ChatChannelUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput> | Prisma.ChatChannelCreateWithoutGroupInput[] | Prisma.ChatChannelUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutGroupInput | Prisma.ChatChannelCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.ChatChannelUpsertWithWhereUniqueWithoutGroupInput | Prisma.ChatChannelUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.ChatChannelCreateManyGroupInputEnvelope
  set?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  disconnect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  delete?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  update?: Prisma.ChatChannelUpdateWithWhereUniqueWithoutGroupInput | Prisma.ChatChannelUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.ChatChannelUpdateManyWithWhereWithoutGroupInput | Prisma.ChatChannelUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
}

export type ChatChannelUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput> | Prisma.ChatChannelCreateWithoutGroupInput[] | Prisma.ChatChannelUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutGroupInput | Prisma.ChatChannelCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.ChatChannelUpsertWithWhereUniqueWithoutGroupInput | Prisma.ChatChannelUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.ChatChannelCreateManyGroupInputEnvelope
  set?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  disconnect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  delete?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  connect?: Prisma.ChatChannelWhereUniqueInput | Prisma.ChatChannelWhereUniqueInput[]
  update?: Prisma.ChatChannelUpdateWithWhereUniqueWithoutGroupInput | Prisma.ChatChannelUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.ChatChannelUpdateManyWithWhereWithoutGroupInput | Prisma.ChatChannelUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
}

export type EnumChatChannelTypeFieldUpdateOperationsInput = {
  set?: $Enums.ChatChannelType
}

export type ChatChannelCreateNestedOneWithoutParticipantsInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutParticipantsInput, Prisma.ChatChannelUncheckedCreateWithoutParticipantsInput>
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutParticipantsInput
  connect?: Prisma.ChatChannelWhereUniqueInput
}

export type ChatChannelUpdateOneRequiredWithoutParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.ChatChannelCreateWithoutParticipantsInput, Prisma.ChatChannelUncheckedCreateWithoutParticipantsInput>
  connectOrCreate?: Prisma.ChatChannelCreateOrConnectWithoutParticipantsInput
  upsert?: Prisma.ChatChannelUpsertWithoutParticipantsInput
  connect?: Prisma.ChatChannelWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ChatChannelUpdateToOneWithWhereWithoutParticipantsInput, Prisma.ChatChannelUpdateWithoutParticipantsInput>, Prisma.ChatChannelUncheckedUpdateWithoutParticipantsInput>
}

export type ChatChannelCreateWithoutIdolInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  group?: Prisma.GroupCreateNestedOneWithoutChatChannelsInput
  participants?: Prisma.ChatParticipantCreateNestedManyWithoutChannelInput
}

export type ChatChannelUncheckedCreateWithoutIdolInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  groupId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  participants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutChannelInput
}

export type ChatChannelCreateOrConnectWithoutIdolInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput>
}

export type ChatChannelCreateManyIdolInputEnvelope = {
  data: Prisma.ChatChannelCreateManyIdolInput | Prisma.ChatChannelCreateManyIdolInput[]
  skipDuplicates?: boolean
}

export type ChatChannelUpsertWithWhereUniqueWithoutIdolInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatChannelUpdateWithoutIdolInput, Prisma.ChatChannelUncheckedUpdateWithoutIdolInput>
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutIdolInput, Prisma.ChatChannelUncheckedCreateWithoutIdolInput>
}

export type ChatChannelUpdateWithWhereUniqueWithoutIdolInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatChannelUpdateWithoutIdolInput, Prisma.ChatChannelUncheckedUpdateWithoutIdolInput>
}

export type ChatChannelUpdateManyWithWhereWithoutIdolInput = {
  where: Prisma.ChatChannelScalarWhereInput
  data: Prisma.XOR<Prisma.ChatChannelUpdateManyMutationInput, Prisma.ChatChannelUncheckedUpdateManyWithoutIdolInput>
}

export type ChatChannelScalarWhereInput = {
  AND?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
  OR?: Prisma.ChatChannelScalarWhereInput[]
  NOT?: Prisma.ChatChannelScalarWhereInput | Prisma.ChatChannelScalarWhereInput[]
  id?: Prisma.StringFilter<"ChatChannel"> | string
  isActive?: Prisma.BoolFilter<"ChatChannel"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ChatChannel"> | Date | string
  version?: Prisma.IntFilter<"ChatChannel"> | number
  name?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  description?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  type?: Prisma.EnumChatChannelTypeFilter<"ChatChannel"> | $Enums.ChatChannelType
  groupId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  idolId?: Prisma.StringNullableFilter<"ChatChannel"> | string | null
  isAnnouncement?: Prisma.BoolFilter<"ChatChannel"> | boolean
  lastMessageAt?: Prisma.DateTimeNullableFilter<"ChatChannel"> | Date | string | null
  firebaseDocId?: Prisma.StringFilter<"ChatChannel"> | string
}

export type ChatChannelCreateWithoutGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  idol?: Prisma.IdolCreateNestedOneWithoutChatChannelsInput
  participants?: Prisma.ChatParticipantCreateNestedManyWithoutChannelInput
}

export type ChatChannelUncheckedCreateWithoutGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  idolId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  participants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutChannelInput
}

export type ChatChannelCreateOrConnectWithoutGroupInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput>
}

export type ChatChannelCreateManyGroupInputEnvelope = {
  data: Prisma.ChatChannelCreateManyGroupInput | Prisma.ChatChannelCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type ChatChannelUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  update: Prisma.XOR<Prisma.ChatChannelUpdateWithoutGroupInput, Prisma.ChatChannelUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutGroupInput, Prisma.ChatChannelUncheckedCreateWithoutGroupInput>
}

export type ChatChannelUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  data: Prisma.XOR<Prisma.ChatChannelUpdateWithoutGroupInput, Prisma.ChatChannelUncheckedUpdateWithoutGroupInput>
}

export type ChatChannelUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.ChatChannelScalarWhereInput
  data: Prisma.XOR<Prisma.ChatChannelUpdateManyMutationInput, Prisma.ChatChannelUncheckedUpdateManyWithoutGroupInput>
}

export type ChatChannelCreateWithoutParticipantsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
  group?: Prisma.GroupCreateNestedOneWithoutChatChannelsInput
  idol?: Prisma.IdolCreateNestedOneWithoutChatChannelsInput
}

export type ChatChannelUncheckedCreateWithoutParticipantsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  groupId?: string | null
  idolId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
}

export type ChatChannelCreateOrConnectWithoutParticipantsInput = {
  where: Prisma.ChatChannelWhereUniqueInput
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutParticipantsInput, Prisma.ChatChannelUncheckedCreateWithoutParticipantsInput>
}

export type ChatChannelUpsertWithoutParticipantsInput = {
  update: Prisma.XOR<Prisma.ChatChannelUpdateWithoutParticipantsInput, Prisma.ChatChannelUncheckedUpdateWithoutParticipantsInput>
  create: Prisma.XOR<Prisma.ChatChannelCreateWithoutParticipantsInput, Prisma.ChatChannelUncheckedCreateWithoutParticipantsInput>
  where?: Prisma.ChatChannelWhereInput
}

export type ChatChannelUpdateToOneWithWhereWithoutParticipantsInput = {
  where?: Prisma.ChatChannelWhereInput
  data: Prisma.XOR<Prisma.ChatChannelUpdateWithoutParticipantsInput, Prisma.ChatChannelUncheckedUpdateWithoutParticipantsInput>
}

export type ChatChannelUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.GroupUpdateOneWithoutChatChannelsNestedInput
  idol?: Prisma.IdolUpdateOneWithoutChatChannelsNestedInput
}

export type ChatChannelUncheckedUpdateWithoutParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  idolId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatChannelCreateManyIdolInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  groupId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
}

export type ChatChannelUpdateWithoutIdolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  group?: Prisma.GroupUpdateOneWithoutChatChannelsNestedInput
  participants?: Prisma.ChatParticipantUpdateManyWithoutChannelNestedInput
}

export type ChatChannelUncheckedUpdateWithoutIdolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  participants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutChannelNestedInput
}

export type ChatChannelUncheckedUpdateManyWithoutIdolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ChatChannelCreateManyGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  name?: string | null
  description?: string | null
  type: $Enums.ChatChannelType
  idolId?: string | null
  isAnnouncement?: boolean
  lastMessageAt?: Date | string | null
  firebaseDocId: string
}

export type ChatChannelUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  idol?: Prisma.IdolUpdateOneWithoutChatChannelsNestedInput
  participants?: Prisma.ChatParticipantUpdateManyWithoutChannelNestedInput
}

export type ChatChannelUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  idolId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
  participants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutChannelNestedInput
}

export type ChatChannelUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.EnumChatChannelTypeFieldUpdateOperationsInput | $Enums.ChatChannelType
  idolId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnnouncement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastMessageAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  firebaseDocId?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ChatChannelCountOutputType
 */

export type ChatChannelCountOutputType = {
  participants: number
}

export type ChatChannelCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participants?: boolean | ChatChannelCountOutputTypeCountParticipantsArgs
}

/**
 * ChatChannelCountOutputType without action
 */
export type ChatChannelCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannelCountOutputType
   */
  select?: Prisma.ChatChannelCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ChatChannelCountOutputType without action
 */
export type ChatChannelCountOutputTypeCountParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatParticipantWhereInput
}


export type ChatChannelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  groupId?: boolean
  idolId?: boolean
  isAnnouncement?: boolean
  lastMessageAt?: boolean
  firebaseDocId?: boolean
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
  participants?: boolean | Prisma.ChatChannel$participantsArgs<ExtArgs>
  _count?: boolean | Prisma.ChatChannelCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["chatChannel"]>

export type ChatChannelSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  groupId?: boolean
  idolId?: boolean
  isAnnouncement?: boolean
  lastMessageAt?: boolean
  firebaseDocId?: boolean
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
}, ExtArgs["result"]["chatChannel"]>

export type ChatChannelSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  groupId?: boolean
  idolId?: boolean
  isAnnouncement?: boolean
  lastMessageAt?: boolean
  firebaseDocId?: boolean
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
}, ExtArgs["result"]["chatChannel"]>

export type ChatChannelSelectScalar = {
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  name?: boolean
  description?: boolean
  type?: boolean
  groupId?: boolean
  idolId?: boolean
  isAnnouncement?: boolean
  lastMessageAt?: boolean
  firebaseDocId?: boolean
}

export type ChatChannelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "isActive" | "createdAt" | "updatedAt" | "version" | "name" | "description" | "type" | "groupId" | "idolId" | "isAnnouncement" | "lastMessageAt" | "firebaseDocId", ExtArgs["result"]["chatChannel"]>
export type ChatChannelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
  participants?: boolean | Prisma.ChatChannel$participantsArgs<ExtArgs>
  _count?: boolean | Prisma.ChatChannelCountOutputTypeDefaultArgs<ExtArgs>
}
export type ChatChannelIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
}
export type ChatChannelIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  group?: boolean | Prisma.ChatChannel$groupArgs<ExtArgs>
  idol?: boolean | Prisma.ChatChannel$idolArgs<ExtArgs>
}

export type $ChatChannelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ChatChannel"
  objects: {
    group: Prisma.$GroupPayload<ExtArgs> | null
    idol: Prisma.$IdolPayload<ExtArgs> | null
    participants: Prisma.$ChatParticipantPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    version: number
    name: string | null
    description: string | null
    type: $Enums.ChatChannelType
    groupId: string | null
    idolId: string | null
    isAnnouncement: boolean
    lastMessageAt: Date | null
    firebaseDocId: string
  }, ExtArgs["result"]["chatChannel"]>
  composites: {}
}

export type ChatChannelGetPayload<S extends boolean | null | undefined | ChatChannelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload, S>

export type ChatChannelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChatChannelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChatChannelCountAggregateInputType | true
  }

export interface ChatChannelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ChatChannel'], meta: { name: 'ChatChannel' } }
  /**
   * Find zero or one ChatChannel that matches the filter.
   * @param {ChatChannelFindUniqueArgs} args - Arguments to find a ChatChannel
   * @example
   * // Get one ChatChannel
   * const chatChannel = await prisma.chatChannel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChatChannelFindUniqueArgs>(args: Prisma.SelectSubset<T, ChatChannelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ChatChannel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChatChannelFindUniqueOrThrowArgs} args - Arguments to find a ChatChannel
   * @example
   * // Get one ChatChannel
   * const chatChannel = await prisma.chatChannel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChatChannelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChatChannelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChatChannel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelFindFirstArgs} args - Arguments to find a ChatChannel
   * @example
   * // Get one ChatChannel
   * const chatChannel = await prisma.chatChannel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChatChannelFindFirstArgs>(args?: Prisma.SelectSubset<T, ChatChannelFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ChatChannel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelFindFirstOrThrowArgs} args - Arguments to find a ChatChannel
   * @example
   * // Get one ChatChannel
   * const chatChannel = await prisma.chatChannel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChatChannelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChatChannelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ChatChannels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ChatChannels
   * const chatChannels = await prisma.chatChannel.findMany()
   * 
   * // Get first 10 ChatChannels
   * const chatChannels = await prisma.chatChannel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const chatChannelWithIdOnly = await prisma.chatChannel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChatChannelFindManyArgs>(args?: Prisma.SelectSubset<T, ChatChannelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ChatChannel.
   * @param {ChatChannelCreateArgs} args - Arguments to create a ChatChannel.
   * @example
   * // Create one ChatChannel
   * const ChatChannel = await prisma.chatChannel.create({
   *   data: {
   *     // ... data to create a ChatChannel
   *   }
   * })
   * 
   */
  create<T extends ChatChannelCreateArgs>(args: Prisma.SelectSubset<T, ChatChannelCreateArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ChatChannels.
   * @param {ChatChannelCreateManyArgs} args - Arguments to create many ChatChannels.
   * @example
   * // Create many ChatChannels
   * const chatChannel = await prisma.chatChannel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChatChannelCreateManyArgs>(args?: Prisma.SelectSubset<T, ChatChannelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ChatChannels and returns the data saved in the database.
   * @param {ChatChannelCreateManyAndReturnArgs} args - Arguments to create many ChatChannels.
   * @example
   * // Create many ChatChannels
   * const chatChannel = await prisma.chatChannel.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ChatChannels and only return the `id`
   * const chatChannelWithIdOnly = await prisma.chatChannel.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChatChannelCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChatChannelCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ChatChannel.
   * @param {ChatChannelDeleteArgs} args - Arguments to delete one ChatChannel.
   * @example
   * // Delete one ChatChannel
   * const ChatChannel = await prisma.chatChannel.delete({
   *   where: {
   *     // ... filter to delete one ChatChannel
   *   }
   * })
   * 
   */
  delete<T extends ChatChannelDeleteArgs>(args: Prisma.SelectSubset<T, ChatChannelDeleteArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ChatChannel.
   * @param {ChatChannelUpdateArgs} args - Arguments to update one ChatChannel.
   * @example
   * // Update one ChatChannel
   * const chatChannel = await prisma.chatChannel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChatChannelUpdateArgs>(args: Prisma.SelectSubset<T, ChatChannelUpdateArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ChatChannels.
   * @param {ChatChannelDeleteManyArgs} args - Arguments to filter ChatChannels to delete.
   * @example
   * // Delete a few ChatChannels
   * const { count } = await prisma.chatChannel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChatChannelDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChatChannelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChatChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ChatChannels
   * const chatChannel = await prisma.chatChannel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChatChannelUpdateManyArgs>(args: Prisma.SelectSubset<T, ChatChannelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ChatChannels and returns the data updated in the database.
   * @param {ChatChannelUpdateManyAndReturnArgs} args - Arguments to update many ChatChannels.
   * @example
   * // Update many ChatChannels
   * const chatChannel = await prisma.chatChannel.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ChatChannels and only return the `id`
   * const chatChannelWithIdOnly = await prisma.chatChannel.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChatChannelUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChatChannelUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ChatChannel.
   * @param {ChatChannelUpsertArgs} args - Arguments to update or create a ChatChannel.
   * @example
   * // Update or create a ChatChannel
   * const chatChannel = await prisma.chatChannel.upsert({
   *   create: {
   *     // ... data to create a ChatChannel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ChatChannel we want to update
   *   }
   * })
   */
  upsert<T extends ChatChannelUpsertArgs>(args: Prisma.SelectSubset<T, ChatChannelUpsertArgs<ExtArgs>>): Prisma.Prisma__ChatChannelClient<runtime.Types.Result.GetResult<Prisma.$ChatChannelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ChatChannels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelCountArgs} args - Arguments to filter ChatChannels to count.
   * @example
   * // Count the number of ChatChannels
   * const count = await prisma.chatChannel.count({
   *   where: {
   *     // ... the filter for the ChatChannels we want to count
   *   }
   * })
  **/
  count<T extends ChatChannelCountArgs>(
    args?: Prisma.Subset<T, ChatChannelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChatChannelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ChatChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChatChannelAggregateArgs>(args: Prisma.Subset<T, ChatChannelAggregateArgs>): Prisma.PrismaPromise<GetChatChannelAggregateType<T>>

  /**
   * Group by ChatChannel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChatChannelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChatChannelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChatChannelGroupByArgs['orderBy'] }
      : { orderBy?: ChatChannelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChatChannelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChatChannelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ChatChannel model
 */
readonly fields: ChatChannelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ChatChannel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChatChannelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  group<T extends Prisma.ChatChannel$groupArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatChannel$groupArgs<ExtArgs>>): Prisma.Prisma__GroupClient<runtime.Types.Result.GetResult<Prisma.$GroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  idol<T extends Prisma.ChatChannel$idolArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatChannel$idolArgs<ExtArgs>>): Prisma.Prisma__IdolClient<runtime.Types.Result.GetResult<Prisma.$IdolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  participants<T extends Prisma.ChatChannel$participantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatChannel$participantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ChatChannel model
 */
export interface ChatChannelFieldRefs {
  readonly id: Prisma.FieldRef<"ChatChannel", 'String'>
  readonly isActive: Prisma.FieldRef<"ChatChannel", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ChatChannel", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ChatChannel", 'DateTime'>
  readonly version: Prisma.FieldRef<"ChatChannel", 'Int'>
  readonly name: Prisma.FieldRef<"ChatChannel", 'String'>
  readonly description: Prisma.FieldRef<"ChatChannel", 'String'>
  readonly type: Prisma.FieldRef<"ChatChannel", 'ChatChannelType'>
  readonly groupId: Prisma.FieldRef<"ChatChannel", 'String'>
  readonly idolId: Prisma.FieldRef<"ChatChannel", 'String'>
  readonly isAnnouncement: Prisma.FieldRef<"ChatChannel", 'Boolean'>
  readonly lastMessageAt: Prisma.FieldRef<"ChatChannel", 'DateTime'>
  readonly firebaseDocId: Prisma.FieldRef<"ChatChannel", 'String'>
}
    

// Custom InputTypes
/**
 * ChatChannel findUnique
 */
export type ChatChannelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter, which ChatChannel to fetch.
   */
  where: Prisma.ChatChannelWhereUniqueInput
}

/**
 * ChatChannel findUniqueOrThrow
 */
export type ChatChannelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter, which ChatChannel to fetch.
   */
  where: Prisma.ChatChannelWhereUniqueInput
}

/**
 * ChatChannel findFirst
 */
export type ChatChannelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter, which ChatChannel to fetch.
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatChannels to fetch.
   */
  orderBy?: Prisma.ChatChannelOrderByWithRelationInput | Prisma.ChatChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChatChannels.
   */
  cursor?: Prisma.ChatChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChatChannels.
   */
  distinct?: Prisma.ChatChannelScalarFieldEnum | Prisma.ChatChannelScalarFieldEnum[]
}

/**
 * ChatChannel findFirstOrThrow
 */
export type ChatChannelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter, which ChatChannel to fetch.
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatChannels to fetch.
   */
  orderBy?: Prisma.ChatChannelOrderByWithRelationInput | Prisma.ChatChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ChatChannels.
   */
  cursor?: Prisma.ChatChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatChannels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ChatChannels.
   */
  distinct?: Prisma.ChatChannelScalarFieldEnum | Prisma.ChatChannelScalarFieldEnum[]
}

/**
 * ChatChannel findMany
 */
export type ChatChannelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter, which ChatChannels to fetch.
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ChatChannels to fetch.
   */
  orderBy?: Prisma.ChatChannelOrderByWithRelationInput | Prisma.ChatChannelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ChatChannels.
   */
  cursor?: Prisma.ChatChannelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ChatChannels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ChatChannels.
   */
  skip?: number
  distinct?: Prisma.ChatChannelScalarFieldEnum | Prisma.ChatChannelScalarFieldEnum[]
}

/**
 * ChatChannel create
 */
export type ChatChannelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * The data needed to create a ChatChannel.
   */
  data: Prisma.XOR<Prisma.ChatChannelCreateInput, Prisma.ChatChannelUncheckedCreateInput>
}

/**
 * ChatChannel createMany
 */
export type ChatChannelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ChatChannels.
   */
  data: Prisma.ChatChannelCreateManyInput | Prisma.ChatChannelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ChatChannel createManyAndReturn
 */
export type ChatChannelCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * The data used to create many ChatChannels.
   */
  data: Prisma.ChatChannelCreateManyInput | Prisma.ChatChannelCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ChatChannel update
 */
export type ChatChannelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * The data needed to update a ChatChannel.
   */
  data: Prisma.XOR<Prisma.ChatChannelUpdateInput, Prisma.ChatChannelUncheckedUpdateInput>
  /**
   * Choose, which ChatChannel to update.
   */
  where: Prisma.ChatChannelWhereUniqueInput
}

/**
 * ChatChannel updateMany
 */
export type ChatChannelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ChatChannels.
   */
  data: Prisma.XOR<Prisma.ChatChannelUpdateManyMutationInput, Prisma.ChatChannelUncheckedUpdateManyInput>
  /**
   * Filter which ChatChannels to update
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * Limit how many ChatChannels to update.
   */
  limit?: number
}

/**
 * ChatChannel updateManyAndReturn
 */
export type ChatChannelUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * The data used to update ChatChannels.
   */
  data: Prisma.XOR<Prisma.ChatChannelUpdateManyMutationInput, Prisma.ChatChannelUncheckedUpdateManyInput>
  /**
   * Filter which ChatChannels to update
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * Limit how many ChatChannels to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ChatChannel upsert
 */
export type ChatChannelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * The filter to search for the ChatChannel to update in case it exists.
   */
  where: Prisma.ChatChannelWhereUniqueInput
  /**
   * In case the ChatChannel found by the `where` argument doesn't exist, create a new ChatChannel with this data.
   */
  create: Prisma.XOR<Prisma.ChatChannelCreateInput, Prisma.ChatChannelUncheckedCreateInput>
  /**
   * In case the ChatChannel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChatChannelUpdateInput, Prisma.ChatChannelUncheckedUpdateInput>
}

/**
 * ChatChannel delete
 */
export type ChatChannelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
  /**
   * Filter which ChatChannel to delete.
   */
  where: Prisma.ChatChannelWhereUniqueInput
}

/**
 * ChatChannel deleteMany
 */
export type ChatChannelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ChatChannels to delete
   */
  where?: Prisma.ChatChannelWhereInput
  /**
   * Limit how many ChatChannels to delete.
   */
  limit?: number
}

/**
 * ChatChannel.group
 */
export type ChatChannel$groupArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Group
   */
  select?: Prisma.GroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Group
   */
  omit?: Prisma.GroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GroupInclude<ExtArgs> | null
  where?: Prisma.GroupWhereInput
}

/**
 * ChatChannel.idol
 */
export type ChatChannel$idolArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Idol
   */
  select?: Prisma.IdolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Idol
   */
  omit?: Prisma.IdolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IdolInclude<ExtArgs> | null
  where?: Prisma.IdolWhereInput
}

/**
 * ChatChannel.participants
 */
export type ChatChannel$participantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatParticipant
   */
  select?: Prisma.ChatParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatParticipant
   */
  omit?: Prisma.ChatParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatParticipantInclude<ExtArgs> | null
  where?: Prisma.ChatParticipantWhereInput
  orderBy?: Prisma.ChatParticipantOrderByWithRelationInput | Prisma.ChatParticipantOrderByWithRelationInput[]
  cursor?: Prisma.ChatParticipantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChatParticipantScalarFieldEnum | Prisma.ChatParticipantScalarFieldEnum[]
}

/**
 * ChatChannel without action
 */
export type ChatChannelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatChannel
   */
  select?: Prisma.ChatChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatChannel
   */
  omit?: Prisma.ChatChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatChannelInclude<ExtArgs> | null
}
