
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FanFollowGroup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FanFollowGroup
 * 
 */
export type FanFollowGroupModel = runtime.Types.Result.DefaultSelection<Prisma.$FanFollowGroupPayload>

export type AggregateFanFollowGroup = {
  _count: FanFollowGroupCountAggregateOutputType | null
  _avg: FanFollowGroupAvgAggregateOutputType | null
  _sum: FanFollowGroupSumAggregateOutputType | null
  _min: FanFollowGroupMinAggregateOutputType | null
  _max: FanFollowGroupMaxAggregateOutputType | null
}

export type FanFollowGroupAvgAggregateOutputType = {
  version: number | null
}

export type FanFollowGroupSumAggregateOutputType = {
  version: number | null
}

export type FanFollowGroupMinAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  fanId: string | null
  groupId: string | null
}

export type FanFollowGroupMaxAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  fanId: string | null
  groupId: string | null
}

export type FanFollowGroupCountAggregateOutputType = {
  id: number
  isActive: number
  createdAt: number
  updatedAt: number
  version: number
  fanId: number
  groupId: number
  _all: number
}


export type FanFollowGroupAvgAggregateInputType = {
  version?: true
}

export type FanFollowGroupSumAggregateInputType = {
  version?: true
}

export type FanFollowGroupMinAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  fanId?: true
  groupId?: true
}

export type FanFollowGroupMaxAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  fanId?: true
  groupId?: true
}

export type FanFollowGroupCountAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  fanId?: true
  groupId?: true
  _all?: true
}

export type FanFollowGroupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FanFollowGroup to aggregate.
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FanFollowGroups to fetch.
   */
  orderBy?: Prisma.FanFollowGroupOrderByWithRelationInput | Prisma.FanFollowGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FanFollowGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FanFollowGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FanFollowGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FanFollowGroups
  **/
  _count?: true | FanFollowGroupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FanFollowGroupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FanFollowGroupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FanFollowGroupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FanFollowGroupMaxAggregateInputType
}

export type GetFanFollowGroupAggregateType<T extends FanFollowGroupAggregateArgs> = {
      [P in keyof T & keyof AggregateFanFollowGroup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFanFollowGroup[P]>
    : Prisma.GetScalarType<T[P], AggregateFanFollowGroup[P]>
}




export type FanFollowGroupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FanFollowGroupWhereInput
  orderBy?: Prisma.FanFollowGroupOrderByWithAggregationInput | Prisma.FanFollowGroupOrderByWithAggregationInput[]
  by: Prisma.FanFollowGroupScalarFieldEnum[] | Prisma.FanFollowGroupScalarFieldEnum
  having?: Prisma.FanFollowGroupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FanFollowGroupCountAggregateInputType | true
  _avg?: FanFollowGroupAvgAggregateInputType
  _sum?: FanFollowGroupSumAggregateInputType
  _min?: FanFollowGroupMinAggregateInputType
  _max?: FanFollowGroupMaxAggregateInputType
}

export type FanFollowGroupGroupByOutputType = {
  id: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  version: number
  fanId: string
  groupId: string
  _count: FanFollowGroupCountAggregateOutputType | null
  _avg: FanFollowGroupAvgAggregateOutputType | null
  _sum: FanFollowGroupSumAggregateOutputType | null
  _min: FanFollowGroupMinAggregateOutputType | null
  _max: FanFollowGroupMaxAggregateOutputType | null
}

type GetFanFollowGroupGroupByPayload<T extends FanFollowGroupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FanFollowGroupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FanFollowGroupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FanFollowGroupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FanFollowGroupGroupByOutputType[P]>
      }
    >
  >



export type FanFollowGroupWhereInput = {
  AND?: Prisma.FanFollowGroupWhereInput | Prisma.FanFollowGroupWhereInput[]
  OR?: Prisma.FanFollowGroupWhereInput[]
  NOT?: Prisma.FanFollowGroupWhereInput | Prisma.FanFollowGroupWhereInput[]
  id?: Prisma.StringFilter<"FanFollowGroup"> | string
  isActive?: Prisma.BoolFilter<"FanFollowGroup"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  version?: Prisma.IntFilter<"FanFollowGroup"> | number
  fanId?: Prisma.StringFilter<"FanFollowGroup"> | string
  groupId?: Prisma.StringFilter<"FanFollowGroup"> | string
  fan?: Prisma.XOR<Prisma.FanScalarRelationFilter, Prisma.FanWhereInput>
  group?: Prisma.XOR<Prisma.GroupScalarRelationFilter, Prisma.GroupWhereInput>
}

export type FanFollowGroupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  fanId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  fan?: Prisma.FanOrderByWithRelationInput
  group?: Prisma.GroupOrderByWithRelationInput
}

export type FanFollowGroupWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fanId_groupId?: Prisma.FanFollowGroupFanIdGroupIdCompoundUniqueInput
  AND?: Prisma.FanFollowGroupWhereInput | Prisma.FanFollowGroupWhereInput[]
  OR?: Prisma.FanFollowGroupWhereInput[]
  NOT?: Prisma.FanFollowGroupWhereInput | Prisma.FanFollowGroupWhereInput[]
  isActive?: Prisma.BoolFilter<"FanFollowGroup"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  version?: Prisma.IntFilter<"FanFollowGroup"> | number
  fanId?: Prisma.StringFilter<"FanFollowGroup"> | string
  groupId?: Prisma.StringFilter<"FanFollowGroup"> | string
  fan?: Prisma.XOR<Prisma.FanScalarRelationFilter, Prisma.FanWhereInput>
  group?: Prisma.XOR<Prisma.GroupScalarRelationFilter, Prisma.GroupWhereInput>
}, "id" | "fanId_groupId">

export type FanFollowGroupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  fanId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  _count?: Prisma.FanFollowGroupCountOrderByAggregateInput
  _avg?: Prisma.FanFollowGroupAvgOrderByAggregateInput
  _max?: Prisma.FanFollowGroupMaxOrderByAggregateInput
  _min?: Prisma.FanFollowGroupMinOrderByAggregateInput
  _sum?: Prisma.FanFollowGroupSumOrderByAggregateInput
}

export type FanFollowGroupScalarWhereWithAggregatesInput = {
  AND?: Prisma.FanFollowGroupScalarWhereWithAggregatesInput | Prisma.FanFollowGroupScalarWhereWithAggregatesInput[]
  OR?: Prisma.FanFollowGroupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FanFollowGroupScalarWhereWithAggregatesInput | Prisma.FanFollowGroupScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FanFollowGroup"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"FanFollowGroup"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FanFollowGroup"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FanFollowGroup"> | Date | string
  version?: Prisma.IntWithAggregatesFilter<"FanFollowGroup"> | number
  fanId?: Prisma.StringWithAggregatesFilter<"FanFollowGroup"> | string
  groupId?: Prisma.StringWithAggregatesFilter<"FanFollowGroup"> | string
}

export type FanFollowGroupCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fan: Prisma.FanCreateNestedOneWithoutFollowedGroupsInput
  group: Prisma.GroupCreateNestedOneWithoutFollowersInput
}

export type FanFollowGroupUncheckedCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fanId: string
  groupId: string
}

export type FanFollowGroupUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fan?: Prisma.FanUpdateOneRequiredWithoutFollowedGroupsNestedInput
  group?: Prisma.GroupUpdateOneRequiredWithoutFollowersNestedInput
}

export type FanFollowGroupUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fanId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FanFollowGroupCreateManyInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fanId: string
  groupId: string
}

export type FanFollowGroupUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
}

export type FanFollowGroupUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fanId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FanFollowGroupListRelationFilter = {
  every?: Prisma.FanFollowGroupWhereInput
  some?: Prisma.FanFollowGroupWhereInput
  none?: Prisma.FanFollowGroupWhereInput
}

export type FanFollowGroupOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FanFollowGroupFanIdGroupIdCompoundUniqueInput = {
  fanId: string
  groupId: string
}

export type FanFollowGroupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  fanId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type FanFollowGroupAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type FanFollowGroupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  fanId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type FanFollowGroupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  fanId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type FanFollowGroupSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type FanFollowGroupCreateNestedManyWithoutFanInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput> | Prisma.FanFollowGroupCreateWithoutFanInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutFanInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutFanInput | Prisma.FanFollowGroupCreateOrConnectWithoutFanInput[]
  createMany?: Prisma.FanFollowGroupCreateManyFanInputEnvelope
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
}

export type FanFollowGroupUncheckedCreateNestedManyWithoutFanInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput> | Prisma.FanFollowGroupCreateWithoutFanInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutFanInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutFanInput | Prisma.FanFollowGroupCreateOrConnectWithoutFanInput[]
  createMany?: Prisma.FanFollowGroupCreateManyFanInputEnvelope
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
}

export type FanFollowGroupUpdateManyWithoutFanNestedInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput> | Prisma.FanFollowGroupCreateWithoutFanInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutFanInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutFanInput | Prisma.FanFollowGroupCreateOrConnectWithoutFanInput[]
  upsert?: Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutFanInput | Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutFanInput[]
  createMany?: Prisma.FanFollowGroupCreateManyFanInputEnvelope
  set?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  disconnect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  delete?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  update?: Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutFanInput | Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutFanInput[]
  updateMany?: Prisma.FanFollowGroupUpdateManyWithWhereWithoutFanInput | Prisma.FanFollowGroupUpdateManyWithWhereWithoutFanInput[]
  deleteMany?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
}

export type FanFollowGroupUncheckedUpdateManyWithoutFanNestedInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput> | Prisma.FanFollowGroupCreateWithoutFanInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutFanInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutFanInput | Prisma.FanFollowGroupCreateOrConnectWithoutFanInput[]
  upsert?: Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutFanInput | Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutFanInput[]
  createMany?: Prisma.FanFollowGroupCreateManyFanInputEnvelope
  set?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  disconnect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  delete?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  update?: Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutFanInput | Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutFanInput[]
  updateMany?: Prisma.FanFollowGroupUpdateManyWithWhereWithoutFanInput | Prisma.FanFollowGroupUpdateManyWithWhereWithoutFanInput[]
  deleteMany?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
}

export type FanFollowGroupCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput> | Prisma.FanFollowGroupCreateWithoutGroupInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput | Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.FanFollowGroupCreateManyGroupInputEnvelope
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
}

export type FanFollowGroupUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput> | Prisma.FanFollowGroupCreateWithoutGroupInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput | Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.FanFollowGroupCreateManyGroupInputEnvelope
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
}

export type FanFollowGroupUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput> | Prisma.FanFollowGroupCreateWithoutGroupInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput | Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutGroupInput | Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.FanFollowGroupCreateManyGroupInputEnvelope
  set?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  disconnect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  delete?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  update?: Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutGroupInput | Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.FanFollowGroupUpdateManyWithWhereWithoutGroupInput | Prisma.FanFollowGroupUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
}

export type FanFollowGroupUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput> | Prisma.FanFollowGroupCreateWithoutGroupInput[] | Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput | Prisma.FanFollowGroupCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutGroupInput | Prisma.FanFollowGroupUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.FanFollowGroupCreateManyGroupInputEnvelope
  set?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  disconnect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  delete?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  connect?: Prisma.FanFollowGroupWhereUniqueInput | Prisma.FanFollowGroupWhereUniqueInput[]
  update?: Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutGroupInput | Prisma.FanFollowGroupUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.FanFollowGroupUpdateManyWithWhereWithoutGroupInput | Prisma.FanFollowGroupUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
}

export type FanFollowGroupCreateWithoutFanInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  group: Prisma.GroupCreateNestedOneWithoutFollowersInput
}

export type FanFollowGroupUncheckedCreateWithoutFanInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  groupId: string
}

export type FanFollowGroupCreateOrConnectWithoutFanInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput>
}

export type FanFollowGroupCreateManyFanInputEnvelope = {
  data: Prisma.FanFollowGroupCreateManyFanInput | Prisma.FanFollowGroupCreateManyFanInput[]
  skipDuplicates?: boolean
}

export type FanFollowGroupUpsertWithWhereUniqueWithoutFanInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  update: Prisma.XOR<Prisma.FanFollowGroupUpdateWithoutFanInput, Prisma.FanFollowGroupUncheckedUpdateWithoutFanInput>
  create: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutFanInput, Prisma.FanFollowGroupUncheckedCreateWithoutFanInput>
}

export type FanFollowGroupUpdateWithWhereUniqueWithoutFanInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateWithoutFanInput, Prisma.FanFollowGroupUncheckedUpdateWithoutFanInput>
}

export type FanFollowGroupUpdateManyWithWhereWithoutFanInput = {
  where: Prisma.FanFollowGroupScalarWhereInput
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateManyMutationInput, Prisma.FanFollowGroupUncheckedUpdateManyWithoutFanInput>
}

export type FanFollowGroupScalarWhereInput = {
  AND?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
  OR?: Prisma.FanFollowGroupScalarWhereInput[]
  NOT?: Prisma.FanFollowGroupScalarWhereInput | Prisma.FanFollowGroupScalarWhereInput[]
  id?: Prisma.StringFilter<"FanFollowGroup"> | string
  isActive?: Prisma.BoolFilter<"FanFollowGroup"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FanFollowGroup"> | Date | string
  version?: Prisma.IntFilter<"FanFollowGroup"> | number
  fanId?: Prisma.StringFilter<"FanFollowGroup"> | string
  groupId?: Prisma.StringFilter<"FanFollowGroup"> | string
}

export type FanFollowGroupCreateWithoutGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fan: Prisma.FanCreateNestedOneWithoutFollowedGroupsInput
}

export type FanFollowGroupUncheckedCreateWithoutGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fanId: string
}

export type FanFollowGroupCreateOrConnectWithoutGroupInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput>
}

export type FanFollowGroupCreateManyGroupInputEnvelope = {
  data: Prisma.FanFollowGroupCreateManyGroupInput | Prisma.FanFollowGroupCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type FanFollowGroupUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  update: Prisma.XOR<Prisma.FanFollowGroupUpdateWithoutGroupInput, Prisma.FanFollowGroupUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.FanFollowGroupCreateWithoutGroupInput, Prisma.FanFollowGroupUncheckedCreateWithoutGroupInput>
}

export type FanFollowGroupUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.FanFollowGroupWhereUniqueInput
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateWithoutGroupInput, Prisma.FanFollowGroupUncheckedUpdateWithoutGroupInput>
}

export type FanFollowGroupUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.FanFollowGroupScalarWhereInput
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateManyMutationInput, Prisma.FanFollowGroupUncheckedUpdateManyWithoutGroupInput>
}

export type FanFollowGroupCreateManyFanInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  groupId: string
}

export type FanFollowGroupUpdateWithoutFanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  group?: Prisma.GroupUpdateOneRequiredWithoutFollowersNestedInput
}

export type FanFollowGroupUncheckedUpdateWithoutFanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FanFollowGroupUncheckedUpdateManyWithoutFanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FanFollowGroupCreateManyGroupInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  fanId: string
}

export type FanFollowGroupUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fan?: Prisma.FanUpdateOneRequiredWithoutFollowedGroupsNestedInput
}

export type FanFollowGroupUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fanId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FanFollowGroupUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  fanId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type FanFollowGroupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  fanId?: boolean
  groupId?: boolean
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fanFollowGroup"]>

export type FanFollowGroupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  fanId?: boolean
  groupId?: boolean
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fanFollowGroup"]>

export type FanFollowGroupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  fanId?: boolean
  groupId?: boolean
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fanFollowGroup"]>

export type FanFollowGroupSelectScalar = {
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  fanId?: boolean
  groupId?: boolean
}

export type FanFollowGroupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "isActive" | "createdAt" | "updatedAt" | "version" | "fanId" | "groupId", ExtArgs["result"]["fanFollowGroup"]>
export type FanFollowGroupInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}
export type FanFollowGroupIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}
export type FanFollowGroupIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fan?: boolean | Prisma.FanDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}

export type $FanFollowGroupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FanFollowGroup"
  objects: {
    fan: Prisma.$FanPayload<ExtArgs>
    group: Prisma.$GroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    version: number
    fanId: string
    groupId: string
  }, ExtArgs["result"]["fanFollowGroup"]>
  composites: {}
}

export type FanFollowGroupGetPayload<S extends boolean | null | undefined | FanFollowGroupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload, S>

export type FanFollowGroupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FanFollowGroupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FanFollowGroupCountAggregateInputType | true
  }

export interface FanFollowGroupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FanFollowGroup'], meta: { name: 'FanFollowGroup' } }
  /**
   * Find zero or one FanFollowGroup that matches the filter.
   * @param {FanFollowGroupFindUniqueArgs} args - Arguments to find a FanFollowGroup
   * @example
   * // Get one FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FanFollowGroupFindUniqueArgs>(args: Prisma.SelectSubset<T, FanFollowGroupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FanFollowGroup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FanFollowGroupFindUniqueOrThrowArgs} args - Arguments to find a FanFollowGroup
   * @example
   * // Get one FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FanFollowGroupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FanFollowGroupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FanFollowGroup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupFindFirstArgs} args - Arguments to find a FanFollowGroup
   * @example
   * // Get one FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FanFollowGroupFindFirstArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupFindFirstArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FanFollowGroup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupFindFirstOrThrowArgs} args - Arguments to find a FanFollowGroup
   * @example
   * // Get one FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FanFollowGroupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FanFollowGroups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FanFollowGroups
   * const fanFollowGroups = await prisma.fanFollowGroup.findMany()
   * 
   * // Get first 10 FanFollowGroups
   * const fanFollowGroups = await prisma.fanFollowGroup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fanFollowGroupWithIdOnly = await prisma.fanFollowGroup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FanFollowGroupFindManyArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FanFollowGroup.
   * @param {FanFollowGroupCreateArgs} args - Arguments to create a FanFollowGroup.
   * @example
   * // Create one FanFollowGroup
   * const FanFollowGroup = await prisma.fanFollowGroup.create({
   *   data: {
   *     // ... data to create a FanFollowGroup
   *   }
   * })
   * 
   */
  create<T extends FanFollowGroupCreateArgs>(args: Prisma.SelectSubset<T, FanFollowGroupCreateArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FanFollowGroups.
   * @param {FanFollowGroupCreateManyArgs} args - Arguments to create many FanFollowGroups.
   * @example
   * // Create many FanFollowGroups
   * const fanFollowGroup = await prisma.fanFollowGroup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FanFollowGroupCreateManyArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FanFollowGroups and returns the data saved in the database.
   * @param {FanFollowGroupCreateManyAndReturnArgs} args - Arguments to create many FanFollowGroups.
   * @example
   * // Create many FanFollowGroups
   * const fanFollowGroup = await prisma.fanFollowGroup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FanFollowGroups and only return the `id`
   * const fanFollowGroupWithIdOnly = await prisma.fanFollowGroup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FanFollowGroupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FanFollowGroup.
   * @param {FanFollowGroupDeleteArgs} args - Arguments to delete one FanFollowGroup.
   * @example
   * // Delete one FanFollowGroup
   * const FanFollowGroup = await prisma.fanFollowGroup.delete({
   *   where: {
   *     // ... filter to delete one FanFollowGroup
   *   }
   * })
   * 
   */
  delete<T extends FanFollowGroupDeleteArgs>(args: Prisma.SelectSubset<T, FanFollowGroupDeleteArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FanFollowGroup.
   * @param {FanFollowGroupUpdateArgs} args - Arguments to update one FanFollowGroup.
   * @example
   * // Update one FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FanFollowGroupUpdateArgs>(args: Prisma.SelectSubset<T, FanFollowGroupUpdateArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FanFollowGroups.
   * @param {FanFollowGroupDeleteManyArgs} args - Arguments to filter FanFollowGroups to delete.
   * @example
   * // Delete a few FanFollowGroups
   * const { count } = await prisma.fanFollowGroup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FanFollowGroupDeleteManyArgs>(args?: Prisma.SelectSubset<T, FanFollowGroupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FanFollowGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FanFollowGroups
   * const fanFollowGroup = await prisma.fanFollowGroup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FanFollowGroupUpdateManyArgs>(args: Prisma.SelectSubset<T, FanFollowGroupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FanFollowGroups and returns the data updated in the database.
   * @param {FanFollowGroupUpdateManyAndReturnArgs} args - Arguments to update many FanFollowGroups.
   * @example
   * // Update many FanFollowGroups
   * const fanFollowGroup = await prisma.fanFollowGroup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FanFollowGroups and only return the `id`
   * const fanFollowGroupWithIdOnly = await prisma.fanFollowGroup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FanFollowGroupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FanFollowGroupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FanFollowGroup.
   * @param {FanFollowGroupUpsertArgs} args - Arguments to update or create a FanFollowGroup.
   * @example
   * // Update or create a FanFollowGroup
   * const fanFollowGroup = await prisma.fanFollowGroup.upsert({
   *   create: {
   *     // ... data to create a FanFollowGroup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FanFollowGroup we want to update
   *   }
   * })
   */
  upsert<T extends FanFollowGroupUpsertArgs>(args: Prisma.SelectSubset<T, FanFollowGroupUpsertArgs<ExtArgs>>): Prisma.Prisma__FanFollowGroupClient<runtime.Types.Result.GetResult<Prisma.$FanFollowGroupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FanFollowGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupCountArgs} args - Arguments to filter FanFollowGroups to count.
   * @example
   * // Count the number of FanFollowGroups
   * const count = await prisma.fanFollowGroup.count({
   *   where: {
   *     // ... the filter for the FanFollowGroups we want to count
   *   }
   * })
  **/
  count<T extends FanFollowGroupCountArgs>(
    args?: Prisma.Subset<T, FanFollowGroupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FanFollowGroupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FanFollowGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FanFollowGroupAggregateArgs>(args: Prisma.Subset<T, FanFollowGroupAggregateArgs>): Prisma.PrismaPromise<GetFanFollowGroupAggregateType<T>>

  /**
   * Group by FanFollowGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FanFollowGroupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FanFollowGroupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FanFollowGroupGroupByArgs['orderBy'] }
      : { orderBy?: FanFollowGroupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FanFollowGroupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFanFollowGroupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FanFollowGroup model
 */
readonly fields: FanFollowGroupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FanFollowGroup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FanFollowGroupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fan<T extends Prisma.FanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FanDefaultArgs<ExtArgs>>): Prisma.Prisma__FanClient<runtime.Types.Result.GetResult<Prisma.$FanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  group<T extends Prisma.GroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GroupDefaultArgs<ExtArgs>>): Prisma.Prisma__GroupClient<runtime.Types.Result.GetResult<Prisma.$GroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FanFollowGroup model
 */
export interface FanFollowGroupFieldRefs {
  readonly id: Prisma.FieldRef<"FanFollowGroup", 'String'>
  readonly isActive: Prisma.FieldRef<"FanFollowGroup", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FanFollowGroup", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FanFollowGroup", 'DateTime'>
  readonly version: Prisma.FieldRef<"FanFollowGroup", 'Int'>
  readonly fanId: Prisma.FieldRef<"FanFollowGroup", 'String'>
  readonly groupId: Prisma.FieldRef<"FanFollowGroup", 'String'>
}
    

// Custom InputTypes
/**
 * FanFollowGroup findUnique
 */
export type FanFollowGroupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter, which FanFollowGroup to fetch.
   */
  where: Prisma.FanFollowGroupWhereUniqueInput
}

/**
 * FanFollowGroup findUniqueOrThrow
 */
export type FanFollowGroupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter, which FanFollowGroup to fetch.
   */
  where: Prisma.FanFollowGroupWhereUniqueInput
}

/**
 * FanFollowGroup findFirst
 */
export type FanFollowGroupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter, which FanFollowGroup to fetch.
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FanFollowGroups to fetch.
   */
  orderBy?: Prisma.FanFollowGroupOrderByWithRelationInput | Prisma.FanFollowGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FanFollowGroups.
   */
  cursor?: Prisma.FanFollowGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FanFollowGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FanFollowGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FanFollowGroups.
   */
  distinct?: Prisma.FanFollowGroupScalarFieldEnum | Prisma.FanFollowGroupScalarFieldEnum[]
}

/**
 * FanFollowGroup findFirstOrThrow
 */
export type FanFollowGroupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter, which FanFollowGroup to fetch.
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FanFollowGroups to fetch.
   */
  orderBy?: Prisma.FanFollowGroupOrderByWithRelationInput | Prisma.FanFollowGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FanFollowGroups.
   */
  cursor?: Prisma.FanFollowGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FanFollowGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FanFollowGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FanFollowGroups.
   */
  distinct?: Prisma.FanFollowGroupScalarFieldEnum | Prisma.FanFollowGroupScalarFieldEnum[]
}

/**
 * FanFollowGroup findMany
 */
export type FanFollowGroupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter, which FanFollowGroups to fetch.
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FanFollowGroups to fetch.
   */
  orderBy?: Prisma.FanFollowGroupOrderByWithRelationInput | Prisma.FanFollowGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FanFollowGroups.
   */
  cursor?: Prisma.FanFollowGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FanFollowGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FanFollowGroups.
   */
  skip?: number
  distinct?: Prisma.FanFollowGroupScalarFieldEnum | Prisma.FanFollowGroupScalarFieldEnum[]
}

/**
 * FanFollowGroup create
 */
export type FanFollowGroupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * The data needed to create a FanFollowGroup.
   */
  data: Prisma.XOR<Prisma.FanFollowGroupCreateInput, Prisma.FanFollowGroupUncheckedCreateInput>
}

/**
 * FanFollowGroup createMany
 */
export type FanFollowGroupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FanFollowGroups.
   */
  data: Prisma.FanFollowGroupCreateManyInput | Prisma.FanFollowGroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FanFollowGroup createManyAndReturn
 */
export type FanFollowGroupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * The data used to create many FanFollowGroups.
   */
  data: Prisma.FanFollowGroupCreateManyInput | Prisma.FanFollowGroupCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FanFollowGroup update
 */
export type FanFollowGroupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * The data needed to update a FanFollowGroup.
   */
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateInput, Prisma.FanFollowGroupUncheckedUpdateInput>
  /**
   * Choose, which FanFollowGroup to update.
   */
  where: Prisma.FanFollowGroupWhereUniqueInput
}

/**
 * FanFollowGroup updateMany
 */
export type FanFollowGroupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FanFollowGroups.
   */
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateManyMutationInput, Prisma.FanFollowGroupUncheckedUpdateManyInput>
  /**
   * Filter which FanFollowGroups to update
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * Limit how many FanFollowGroups to update.
   */
  limit?: number
}

/**
 * FanFollowGroup updateManyAndReturn
 */
export type FanFollowGroupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * The data used to update FanFollowGroups.
   */
  data: Prisma.XOR<Prisma.FanFollowGroupUpdateManyMutationInput, Prisma.FanFollowGroupUncheckedUpdateManyInput>
  /**
   * Filter which FanFollowGroups to update
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * Limit how many FanFollowGroups to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FanFollowGroup upsert
 */
export type FanFollowGroupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * The filter to search for the FanFollowGroup to update in case it exists.
   */
  where: Prisma.FanFollowGroupWhereUniqueInput
  /**
   * In case the FanFollowGroup found by the `where` argument doesn't exist, create a new FanFollowGroup with this data.
   */
  create: Prisma.XOR<Prisma.FanFollowGroupCreateInput, Prisma.FanFollowGroupUncheckedCreateInput>
  /**
   * In case the FanFollowGroup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FanFollowGroupUpdateInput, Prisma.FanFollowGroupUncheckedUpdateInput>
}

/**
 * FanFollowGroup delete
 */
export type FanFollowGroupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
  /**
   * Filter which FanFollowGroup to delete.
   */
  where: Prisma.FanFollowGroupWhereUniqueInput
}

/**
 * FanFollowGroup deleteMany
 */
export type FanFollowGroupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FanFollowGroups to delete
   */
  where?: Prisma.FanFollowGroupWhereInput
  /**
   * Limit how many FanFollowGroups to delete.
   */
  limit?: number
}

/**
 * FanFollowGroup without action
 */
export type FanFollowGroupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FanFollowGroup
   */
  select?: Prisma.FanFollowGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FanFollowGroup
   */
  omit?: Prisma.FanFollowGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanFollowGroupInclude<ExtArgs> | null
}
