
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserAvgAggregateOutputType = {
  version: number | null
}

export type UserSumAggregateOutputType = {
  version: number | null
}

export type UserMinAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  email: string | null
  password: string | null
  role: $Enums.Role | null
  deviceToken: string | null
  isDeleted: boolean | null
  isOnline: boolean | null
}

export type UserMaxAggregateOutputType = {
  id: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  version: number | null
  email: string | null
  password: string | null
  role: $Enums.Role | null
  deviceToken: string | null
  isDeleted: boolean | null
  isOnline: boolean | null
}

export type UserCountAggregateOutputType = {
  id: number
  isActive: number
  createdAt: number
  updatedAt: number
  version: number
  email: number
  password: number
  role: number
  deviceToken: number
  isDeleted: number
  isOnline: number
  _all: number
}


export type UserAvgAggregateInputType = {
  version?: true
}

export type UserSumAggregateInputType = {
  version?: true
}

export type UserMinAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  email?: true
  password?: true
  role?: true
  deviceToken?: true
  isDeleted?: true
  isOnline?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  email?: true
  password?: true
  role?: true
  deviceToken?: true
  isDeleted?: true
  isOnline?: true
}

export type UserCountAggregateInputType = {
  id?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  version?: true
  email?: true
  password?: true
  role?: true
  deviceToken?: true
  isDeleted?: true
  isOnline?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _avg?: UserAvgAggregateInputType
  _sum?: UserSumAggregateInputType
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: string
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  version: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken: string | null
  isDeleted: boolean
  isOnline: boolean
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.StringFilter<"User"> | string
  isActive?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  version?: Prisma.IntFilter<"User"> | number
  email?: Prisma.StringFilter<"User"> | string
  password?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  deviceToken?: Prisma.StringNullableFilter<"User"> | string | null
  isDeleted?: Prisma.BoolFilter<"User"> | boolean
  isOnline?: Prisma.BoolFilter<"User"> | boolean
  social_accounts?: Prisma.SocialAccountListRelationFilter
  verifications?: Prisma.VerificationListRelationFilter
  fan?: Prisma.XOR<Prisma.FanNullableScalarRelationFilter, Prisma.FanWhereInput> | null
  idol?: Prisma.XOR<Prisma.IdolNullableScalarRelationFilter, Prisma.IdolWhereInput> | null
  chatParticipants?: Prisma.ChatParticipantListRelationFilter
  carts?: Prisma.CartListRelationFilter
  orders?: Prisma.OrderListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  deviceToken?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  social_accounts?: Prisma.SocialAccountOrderByRelationAggregateInput
  verifications?: Prisma.VerificationOrderByRelationAggregateInput
  fan?: Prisma.FanOrderByWithRelationInput
  idol?: Prisma.IdolOrderByWithRelationInput
  chatParticipants?: Prisma.ChatParticipantOrderByRelationAggregateInput
  carts?: Prisma.CartOrderByRelationAggregateInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  isActive?: Prisma.BoolFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"User"> | Date | string
  version?: Prisma.IntFilter<"User"> | number
  password?: Prisma.StringFilter<"User"> | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  deviceToken?: Prisma.StringNullableFilter<"User"> | string | null
  isDeleted?: Prisma.BoolFilter<"User"> | boolean
  isOnline?: Prisma.BoolFilter<"User"> | boolean
  social_accounts?: Prisma.SocialAccountListRelationFilter
  verifications?: Prisma.VerificationListRelationFilter
  fan?: Prisma.XOR<Prisma.FanNullableScalarRelationFilter, Prisma.FanWhereInput> | null
  idol?: Prisma.XOR<Prisma.IdolNullableScalarRelationFilter, Prisma.IdolWhereInput> | null
  chatParticipants?: Prisma.ChatParticipantListRelationFilter
  carts?: Prisma.CartListRelationFilter
  orders?: Prisma.OrderListRelationFilter
}, "id" | "email">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  deviceToken?: Prisma.SortOrderInput | Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _avg?: Prisma.UserAvgOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
  _sum?: Prisma.UserSumOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"User"> | string
  isActive?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  version?: Prisma.IntWithAggregatesFilter<"User"> | number
  email?: Prisma.StringWithAggregatesFilter<"User"> | string
  password?: Prisma.StringWithAggregatesFilter<"User"> | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  deviceToken?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  isDeleted?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  isOnline?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
}

export type UserCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateManyInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  deviceToken?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
}

export type UserAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  deviceToken?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  version?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  role?: Prisma.SortOrder
  deviceToken?: Prisma.SortOrder
  isDeleted?: Prisma.SortOrder
  isOnline?: Prisma.SortOrder
}

export type UserSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type UserNullableScalarRelationFilter = {
  is?: Prisma.UserWhereInput | null
  isNot?: Prisma.UserWhereInput | null
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type UserCreateNestedOneWithoutVerificationsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutVerificationsInput, Prisma.UserUncheckedCreateWithoutVerificationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutVerificationsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneWithoutVerificationsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutVerificationsInput, Prisma.UserUncheckedCreateWithoutVerificationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutVerificationsInput
  upsert?: Prisma.UserUpsertWithoutVerificationsInput
  disconnect?: Prisma.UserWhereInput | boolean
  delete?: Prisma.UserWhereInput | boolean
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutVerificationsInput, Prisma.UserUpdateWithoutVerificationsInput>, Prisma.UserUncheckedUpdateWithoutVerificationsInput>
}

export type UserCreateNestedOneWithoutSocial_accountsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSocial_accountsInput, Prisma.UserUncheckedCreateWithoutSocial_accountsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSocial_accountsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutSocial_accountsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutSocial_accountsInput, Prisma.UserUncheckedCreateWithoutSocial_accountsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutSocial_accountsInput
  upsert?: Prisma.UserUpsertWithoutSocial_accountsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutSocial_accountsInput, Prisma.UserUpdateWithoutSocial_accountsInput>, Prisma.UserUncheckedUpdateWithoutSocial_accountsInput>
}

export type UserCreateNestedOneWithoutFanInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFanInput, Prisma.UserUncheckedCreateWithoutFanInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFanInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutFanNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutFanInput, Prisma.UserUncheckedCreateWithoutFanInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutFanInput
  upsert?: Prisma.UserUpsertWithoutFanInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutFanInput, Prisma.UserUpdateWithoutFanInput>, Prisma.UserUncheckedUpdateWithoutFanInput>
}

export type UserCreateNestedOneWithoutIdolInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutIdolInput, Prisma.UserUncheckedCreateWithoutIdolInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutIdolInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutIdolNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutIdolInput, Prisma.UserUncheckedCreateWithoutIdolInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutIdolInput
  upsert?: Prisma.UserUpsertWithoutIdolInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutIdolInput, Prisma.UserUpdateWithoutIdolInput>, Prisma.UserUncheckedUpdateWithoutIdolInput>
}

export type UserCreateNestedOneWithoutChatParticipantsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutChatParticipantsInput, Prisma.UserUncheckedCreateWithoutChatParticipantsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutChatParticipantsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutChatParticipantsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutChatParticipantsInput, Prisma.UserUncheckedCreateWithoutChatParticipantsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutChatParticipantsInput
  upsert?: Prisma.UserUpsertWithoutChatParticipantsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutChatParticipantsInput, Prisma.UserUpdateWithoutChatParticipantsInput>, Prisma.UserUncheckedUpdateWithoutChatParticipantsInput>
}

export type UserCreateNestedOneWithoutCartsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCartsInput, Prisma.UserUncheckedCreateWithoutCartsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCartsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutCartsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutCartsInput, Prisma.UserUncheckedCreateWithoutCartsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutCartsInput
  upsert?: Prisma.UserUpsertWithoutCartsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutCartsInput, Prisma.UserUpdateWithoutCartsInput>, Prisma.UserUncheckedUpdateWithoutCartsInput>
}

export type UserCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutOrdersInput, Prisma.UserUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutOrdersInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutOrdersInput, Prisma.UserUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.UserUpsertWithoutOrdersInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutOrdersInput, Prisma.UserUpdateWithoutOrdersInput>, Prisma.UserUncheckedUpdateWithoutOrdersInput>
}

export type UserCreateWithoutVerificationsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutVerificationsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutVerificationsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutVerificationsInput, Prisma.UserUncheckedCreateWithoutVerificationsInput>
}

export type UserUpsertWithoutVerificationsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutVerificationsInput, Prisma.UserUncheckedUpdateWithoutVerificationsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutVerificationsInput, Prisma.UserUncheckedCreateWithoutVerificationsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutVerificationsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutVerificationsInput, Prisma.UserUncheckedUpdateWithoutVerificationsInput>
}

export type UserUpdateWithoutVerificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutVerificationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutSocial_accountsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutSocial_accountsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutSocial_accountsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutSocial_accountsInput, Prisma.UserUncheckedCreateWithoutSocial_accountsInput>
}

export type UserUpsertWithoutSocial_accountsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutSocial_accountsInput, Prisma.UserUncheckedUpdateWithoutSocial_accountsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutSocial_accountsInput, Prisma.UserUncheckedCreateWithoutSocial_accountsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutSocial_accountsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutSocial_accountsInput, Prisma.UserUncheckedUpdateWithoutSocial_accountsInput>
}

export type UserUpdateWithoutSocial_accountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutSocial_accountsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutFanInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutFanInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutFanInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutFanInput, Prisma.UserUncheckedCreateWithoutFanInput>
}

export type UserUpsertWithoutFanInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutFanInput, Prisma.UserUncheckedUpdateWithoutFanInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutFanInput, Prisma.UserUncheckedCreateWithoutFanInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutFanInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutFanInput, Prisma.UserUncheckedUpdateWithoutFanInput>
}

export type UserUpdateWithoutFanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutFanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutIdolInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutIdolInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutIdolInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutIdolInput, Prisma.UserUncheckedCreateWithoutIdolInput>
}

export type UserUpsertWithoutIdolInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutIdolInput, Prisma.UserUncheckedUpdateWithoutIdolInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutIdolInput, Prisma.UserUncheckedCreateWithoutIdolInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutIdolInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutIdolInput, Prisma.UserUncheckedUpdateWithoutIdolInput>
}

export type UserUpdateWithoutIdolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutIdolInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutChatParticipantsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutChatParticipantsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutChatParticipantsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutChatParticipantsInput, Prisma.UserUncheckedCreateWithoutChatParticipantsInput>
}

export type UserUpsertWithoutChatParticipantsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutChatParticipantsInput, Prisma.UserUncheckedUpdateWithoutChatParticipantsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutChatParticipantsInput, Prisma.UserUncheckedCreateWithoutChatParticipantsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutChatParticipantsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutChatParticipantsInput, Prisma.UserUncheckedUpdateWithoutChatParticipantsInput>
}

export type UserUpdateWithoutChatParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutChatParticipantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutCartsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderCreateNestedManyWithoutBuyerInput
}

export type UserUncheckedCreateWithoutCartsInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutBuyerInput
}

export type UserCreateOrConnectWithoutCartsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutCartsInput, Prisma.UserUncheckedCreateWithoutCartsInput>
}

export type UserUpsertWithoutCartsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutCartsInput, Prisma.UserUncheckedUpdateWithoutCartsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutCartsInput, Prisma.UserUncheckedCreateWithoutCartsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutCartsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutCartsInput, Prisma.UserUncheckedUpdateWithoutCartsInput>
}

export type UserUpdateWithoutCartsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUpdateManyWithoutBuyerNestedInput
}

export type UserUncheckedUpdateWithoutCartsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutBuyerNestedInput
}

export type UserCreateWithoutOrdersInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationCreateNestedManyWithoutUserInput
  fan?: Prisma.FanCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantCreateNestedManyWithoutUserInput
  carts?: Prisma.CartCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutOrdersInput = {
  id?: string
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  version?: number
  email: string
  password: string
  role: $Enums.Role
  deviceToken?: string | null
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: Prisma.SocialAccountUncheckedCreateNestedManyWithoutUserInput
  verifications?: Prisma.VerificationUncheckedCreateNestedManyWithoutUserInput
  fan?: Prisma.FanUncheckedCreateNestedOneWithoutUserInput
  idol?: Prisma.IdolUncheckedCreateNestedOneWithoutUserInput
  chatParticipants?: Prisma.ChatParticipantUncheckedCreateNestedManyWithoutUserInput
  carts?: Prisma.CartUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutOrdersInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutOrdersInput, Prisma.UserUncheckedCreateWithoutOrdersInput>
}

export type UserUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutOrdersInput, Prisma.UserUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutOrdersInput, Prisma.UserUncheckedCreateWithoutOrdersInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutOrdersInput, Prisma.UserUncheckedUpdateWithoutOrdersInput>
}

export type UserUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  deviceToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isDeleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOnline?: Prisma.BoolFieldUpdateOperationsInput | boolean
  social_accounts?: Prisma.SocialAccountUncheckedUpdateManyWithoutUserNestedInput
  verifications?: Prisma.VerificationUncheckedUpdateManyWithoutUserNestedInput
  fan?: Prisma.FanUncheckedUpdateOneWithoutUserNestedInput
  idol?: Prisma.IdolUncheckedUpdateOneWithoutUserNestedInput
  chatParticipants?: Prisma.ChatParticipantUncheckedUpdateManyWithoutUserNestedInput
  carts?: Prisma.CartUncheckedUpdateManyWithoutUserNestedInput
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  social_accounts: number
  verifications: number
  chatParticipants: number
  carts: number
  orders: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  social_accounts?: boolean | UserCountOutputTypeCountSocial_accountsArgs
  verifications?: boolean | UserCountOutputTypeCountVerificationsArgs
  chatParticipants?: boolean | UserCountOutputTypeCountChatParticipantsArgs
  carts?: boolean | UserCountOutputTypeCountCartsArgs
  orders?: boolean | UserCountOutputTypeCountOrdersArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountSocial_accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SocialAccountWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountVerificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VerificationWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountChatParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatParticipantWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountCartsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CartWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  deviceToken?: boolean
  isDeleted?: boolean
  isOnline?: boolean
  social_accounts?: boolean | Prisma.User$social_accountsArgs<ExtArgs>
  verifications?: boolean | Prisma.User$verificationsArgs<ExtArgs>
  fan?: boolean | Prisma.User$fanArgs<ExtArgs>
  idol?: boolean | Prisma.User$idolArgs<ExtArgs>
  chatParticipants?: boolean | Prisma.User$chatParticipantsArgs<ExtArgs>
  carts?: boolean | Prisma.User$cartsArgs<ExtArgs>
  orders?: boolean | Prisma.User$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  deviceToken?: boolean
  isDeleted?: boolean
  isOnline?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  deviceToken?: boolean
  isDeleted?: boolean
  isOnline?: boolean
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  version?: boolean
  email?: boolean
  password?: boolean
  role?: boolean
  deviceToken?: boolean
  isDeleted?: boolean
  isOnline?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "isActive" | "createdAt" | "updatedAt" | "version" | "email" | "password" | "role" | "deviceToken" | "isDeleted" | "isOnline", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  social_accounts?: boolean | Prisma.User$social_accountsArgs<ExtArgs>
  verifications?: boolean | Prisma.User$verificationsArgs<ExtArgs>
  fan?: boolean | Prisma.User$fanArgs<ExtArgs>
  idol?: boolean | Prisma.User$idolArgs<ExtArgs>
  chatParticipants?: boolean | Prisma.User$chatParticipantsArgs<ExtArgs>
  carts?: boolean | Prisma.User$cartsArgs<ExtArgs>
  orders?: boolean | Prisma.User$ordersArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    social_accounts: Prisma.$SocialAccountPayload<ExtArgs>[]
    verifications: Prisma.$VerificationPayload<ExtArgs>[]
    fan: Prisma.$FanPayload<ExtArgs> | null
    idol: Prisma.$IdolPayload<ExtArgs> | null
    chatParticipants: Prisma.$ChatParticipantPayload<ExtArgs>[]
    carts: Prisma.$CartPayload<ExtArgs>[]
    orders: Prisma.$OrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    isActive: boolean
    createdAt: Date
    updatedAt: Date
    version: number
    email: string
    password: string
    role: $Enums.Role
    deviceToken: string | null
    isDeleted: boolean
    isOnline: boolean
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  social_accounts<T extends Prisma.User$social_accountsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$social_accountsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SocialAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  verifications<T extends Prisma.User$verificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$verificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VerificationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  fan<T extends Prisma.User$fanArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$fanArgs<ExtArgs>>): Prisma.Prisma__FanClient<runtime.Types.Result.GetResult<Prisma.$FanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  idol<T extends Prisma.User$idolArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$idolArgs<ExtArgs>>): Prisma.Prisma__IdolClient<runtime.Types.Result.GetResult<Prisma.$IdolPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  chatParticipants<T extends Prisma.User$chatParticipantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$chatParticipantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  carts<T extends Prisma.User$cartsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$cartsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.User$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'String'>
  readonly isActive: Prisma.FieldRef<"User", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly version: Prisma.FieldRef<"User", 'Int'>
  readonly email: Prisma.FieldRef<"User", 'String'>
  readonly password: Prisma.FieldRef<"User", 'String'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly deviceToken: Prisma.FieldRef<"User", 'String'>
  readonly isDeleted: Prisma.FieldRef<"User", 'Boolean'>
  readonly isOnline: Prisma.FieldRef<"User", 'Boolean'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.social_accounts
 */
export type User$social_accountsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SocialAccount
   */
  select?: Prisma.SocialAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SocialAccount
   */
  omit?: Prisma.SocialAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SocialAccountInclude<ExtArgs> | null
  where?: Prisma.SocialAccountWhereInput
  orderBy?: Prisma.SocialAccountOrderByWithRelationInput | Prisma.SocialAccountOrderByWithRelationInput[]
  cursor?: Prisma.SocialAccountWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SocialAccountScalarFieldEnum | Prisma.SocialAccountScalarFieldEnum[]
}

/**
 * User.verifications
 */
export type User$verificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verification
   */
  select?: Prisma.VerificationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verification
   */
  omit?: Prisma.VerificationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerificationInclude<ExtArgs> | null
  where?: Prisma.VerificationWhereInput
  orderBy?: Prisma.VerificationOrderByWithRelationInput | Prisma.VerificationOrderByWithRelationInput[]
  cursor?: Prisma.VerificationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VerificationScalarFieldEnum | Prisma.VerificationScalarFieldEnum[]
}

/**
 * User.fan
 */
export type User$fanArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Fan
   */
  select?: Prisma.FanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Fan
   */
  omit?: Prisma.FanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FanInclude<ExtArgs> | null
  where?: Prisma.FanWhereInput
}

/**
 * User.idol
 */
export type User$idolArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Idol
   */
  select?: Prisma.IdolSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Idol
   */
  omit?: Prisma.IdolOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IdolInclude<ExtArgs> | null
  where?: Prisma.IdolWhereInput
}

/**
 * User.chatParticipants
 */
export type User$chatParticipantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatParticipant
   */
  select?: Prisma.ChatParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatParticipant
   */
  omit?: Prisma.ChatParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatParticipantInclude<ExtArgs> | null
  where?: Prisma.ChatParticipantWhereInput
  orderBy?: Prisma.ChatParticipantOrderByWithRelationInput | Prisma.ChatParticipantOrderByWithRelationInput[]
  cursor?: Prisma.ChatParticipantWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChatParticipantScalarFieldEnum | Prisma.ChatParticipantScalarFieldEnum[]
}

/**
 * User.carts
 */
export type User$cartsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Cart
   */
  select?: Prisma.CartSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Cart
   */
  omit?: Prisma.CartOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartInclude<ExtArgs> | null
  where?: Prisma.CartWhereInput
  orderBy?: Prisma.CartOrderByWithRelationInput | Prisma.CartOrderByWithRelationInput[]
  cursor?: Prisma.CartWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CartScalarFieldEnum | Prisma.CartScalarFieldEnum[]
}

/**
 * User.orders
 */
export type User$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
