
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model SocialAccount
 * 
 */
export type SocialAccount = Prisma.SocialAccountModel
/**
 * Model Community
 * 
 */
export type Community = Prisma.CommunityModel
/**
 * Model CommunityFollower
 * 
 */
export type CommunityFollower = Prisma.CommunityFollowerModel
/**
 * Model ChatChannel
 * 
 */
export type ChatChannel = Prisma.ChatChannelModel
/**
 * Model ChatParticipant
 * 
 */
export type ChatParticipant = Prisma.ChatParticipantModel
/**
 * Model ChatMessage
 * 
 */
export type ChatMessage = Prisma.ChatMessageModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Comment
 * 
 */
export type Comment = Prisma.CommentModel
/**
 * Model PostLike
 * 
 */
export type PostLike = Prisma.PostLikeModel
/**
 * Model PostView
 * 
 */
export type PostView = Prisma.PostViewModel
/**
 * Model Shop
 * 
 */
export type Shop = Prisma.ShopModel
/**
 * Model ProductType
 * 
 */
export type ProductType = Prisma.ProductTypeModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model Cart
 * 
 */
export type Cart = Prisma.CartModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model PaymentTransaction
 * 
 */
export type PaymentTransaction = Prisma.PaymentTransactionModel
/**
 * Model Province
 * 
 */
export type Province = Prisma.ProvinceModel
/**
 * Model District
 * 
 */
export type District = Prisma.DistrictModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
