
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model SocialAccount
 * 
 */
export type SocialAccount = Prisma.SocialAccountModel
/**
 * Model Fan
 * 
 */
export type Fan = Prisma.FanModel
/**
 * Model Idol
 * 
 */
export type Idol = Prisma.IdolModel
/**
 * Model Group
 * 
 */
export type Group = Prisma.GroupModel
/**
 * Model FanFollowGroup
 * 
 */
export type FanFollowGroup = Prisma.FanFollowGroupModel
/**
 * Model ChatChannel
 * 
 */
export type ChatChannel = Prisma.ChatChannelModel
/**
 * Model ChatParticipant
 * 
 */
export type ChatParticipant = Prisma.ChatParticipantModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductCategory
 * 
 */
export type ProductCategory = Prisma.ProductCategoryModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model Cart
 * 
 */
export type Cart = Prisma.CartModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
