
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  FAN: 'FAN',
  ADMIN: 'ADMIN',
  IDOL: 'IDOL'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const VerificationType = {
  FIND_EMAIL: 'FIND_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_ACCOUNT: 'REGISTER_ACCOUNT',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD'
} as const

export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType]


export const OrderStatus = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PAID: 'PAID',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const PaymentTransactionStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED'
} as const

export type PaymentTransactionStatus = (typeof PaymentTransactionStatus)[keyof typeof PaymentTransactionStatus]


export const PaymentMethod = {
  CREDIT: 'CREDIT',
  COD: 'COD'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const CommunityType = {
  SOLO: 'SOLO',
  GROUP: 'GROUP'
} as const

export type CommunityType = (typeof CommunityType)[keyof typeof CommunityType]
