
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  FAN: 'FAN',
  ADMIN: 'ADMIN',
  IDOL: 'IDOL'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const VerificationType = {
  FIND_EMAIL: 'FIND_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_ACCOUNT: 'REGISTER_ACCOUNT',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
} as const

export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType]


export const SocialAccountProvider = {
  GOOGLE: 'GOOGLE',
  FACEBOOK: 'FACEBOOK'
} as const

export type SocialAccountProvider = (typeof SocialAccountProvider)[keyof typeof SocialAccountProvider]


export const ChatRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type ChatRole = (typeof ChatRole)[keyof typeof ChatRole]


export const OrderStatus = {
  pending: 'pending',
  paid: 'paid',
  shipping: 'shipping',
  delivered: 'delivered',
  cancelled: 'cancelled',
  refunded: 'refunded'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const PaymentTransactionStatus = {
  pending: 'pending',
  success: 'success',
  failed: 'failed',
  refunded: 'refunded'
} as const

export type PaymentTransactionStatus = (typeof PaymentTransactionStatus)[keyof typeof PaymentTransactionStatus]
