
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  FAN: 'FAN',
  ADMIN: 'ADMIN',
  IDOL: 'IDOL'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const VerificationType = {
  FIND_EMAIL: 'FIND_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_ACCOUNT: 'REGISTER_ACCOUNT',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
} as const

export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType]


export const SocialAccountProvider = {
  GOOGLE: 'GOOGLE',
  FACEBOOK: 'FACEBOOK'
} as const

export type SocialAccountProvider = (typeof SocialAccountProvider)[keyof typeof SocialAccountProvider]


export const ChatChannelType = {
  DIRECT: 'DIRECT',
  GROUP: 'GROUP',
  ANNOUNCEMENT: 'ANNOUNCEMENT'
} as const

export type ChatChannelType = (typeof ChatChannelType)[keyof typeof ChatChannelType]


export const ChatRole = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
} as const

export type ChatRole = (typeof ChatRole)[keyof typeof ChatRole]


export const OrderStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]
