services:
  server:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: ventidole-server
    env_file:
      - ../../.env
    restart: always
# trigger workflow
