import { randomUUID } from 'crypto';

/**
 * Cart ID Value Object
 *
 * Represents a unique identifier for a Cart aggregate.
 *
 * Pattern: cuid() generated by Prisma
 */
export class CartId {
  private readonly _value: string;

  private constructor(value: string) {
    if (!value || value.trim().length === 0) {
      throw new Error('CartId cannot be empty');
    }
    this._value = value;
  }

  /**
   * Generate new CartId (for creation)
   */
  static generate(): CartId {
    return new CartId(randomUUID());
  }

  /**
   * Create from existing string (from database)
   */
  static fromString(value: string): CartId {
    return new CartId(value);
  }

  get value(): string {
    return this._value;
  }

  equals(other: CartId): boolean {
    if (!(other instanceof CartId)) {
      return false;
    }
    return this._value === other._value;
  }

  toString(): string {
    return this._value;
  }
}
